"""
╔══════════════════════════════════════════════════════════════════╗
║  FAKE NEWS DETECTOR — Streamlit Web App  (v3)                   ║
║  Compatible with F6_v2.py model output                          ║
║  Run: streamlit run app.py                                      ║
╚══════════════════════════════════════════════════════════════════╝
"""

import os, re, string, pickle, warnings
import numpy as np
import streamlit as st
import nltk

for pkg in ["stopwords", "punkt", "punkt_tab", "wordnet", "omw-1.4"]:
    nltk.download(pkg, quiet=True)

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

warnings.filterwarnings("ignore")

MODEL_PKL = "linsvm_model.pkl"
VEC_PKL   = "tfidf_vectorizer.pkl"
META_PKL  = "model_meta.pkl"

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

# ── Probe headlines for fallback label detection ─────────────────
PROBE_FAKE = [
    "Mark Zuckerberg Will Give You $5,000 if You Share This Post",
    "Obama Signs Executive Order Banning the Pledge of Allegiance",
    "Pope Francis Shocks World Endorses Donald Trump for President",
    "Bill Gates Wants to Depopulate the World Using Vaccines",
    "NASA Admits to Chemtrails Spraying Program to Control Population",
    "Hillary Clinton Ran a Child Trafficking Ring from a Pizza Restaurant",
    "Scientists Discover Cure for Cancer But Big Pharma Is Hiding It",
    "Breaking: Martial Law Declared in Texas Following Border Invasion",
    "Soros Funds Antifa to Overthrow the US Government This Weekend",
    "Vaccines Cause Autism Confirmed by CDC Whistleblower",
]
PROBE_REAL = [
    "Federal Reserve raises interest rates by 25 basis points",
    "Ukraine and Russia hold ceasefire talks in Turkey",
    "Apple reports record quarterly revenue driven by iPhone sales",
    "WHO declares end to COVID-19 global health emergency",
    "NASA successfully launches Artemis mission to lunar orbit",
    "Congress passes bipartisan infrastructure spending bill",
    "Supreme Court rules on affirmative action in college admissions",
    "Oil prices drop after OPEC agrees to increase production",
    "Tech layoffs continue as Microsoft cuts 10,000 jobs",
    "UN Security Council votes on resolution condemning attacks",
]

# ── Text cleaning ─────────────────────────────────────────────────
def clean_text(text: str) -> str:
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(r"<.*?>",   " ", text)
    text = re.sub(r"\S+@\S+", " ", text)
    text = re.sub(r"@\w+",    " ", text)
    text = re.sub(r"#",       " ", text)
    text = re.sub(r"\d+",     " ", text)
    text = text.translate(str.maketrans("", "", string.punctuation))
    text = re.sub(r"\s+",     " ", text).strip()
    tokens = word_tokenize(text)
    tokens = [t for t in tokens if t not in stop_words and len(t) > 2]
    tokens = [lemmatizer.lemmatize(t) for t in tokens]
    return " ".join(tokens)


# ── Fallback probe-based label detection ─────────────────────────
def probe_detect_label_map(model, vec):
    classes = sorted(model.classes_.tolist())
    c0, c1  = classes[0], classes[1]

    def score(fake_int):
        real_int = c1 if fake_int == c0 else c0
        hits = 0
        for t in PROBE_FAKE:
            x = vec.transform([clean_text(t)])
            hits += (model.predict(x)[0] == fake_int)
        for t in PROBE_REAL:
            x = vec.transform([clean_text(t)])
            hits += (model.predict(x)[0] == real_int)
        return hits

    s0, s1 = score(c0), score(c1)
    if s0 >= s1:
        return {c0: "FAKE", c1: "REAL"}, s0
    return {c1: "FAKE", c0: "REAL"}, s1


# ── Model loading ─────────────────────────────────────────────────
@st.cache_resource(show_spinner="Loading model…")
def load_model():
    if not os.path.exists(MODEL_PKL) or not os.path.exists(VEC_PKL):
        return None, None, None, None

    model = pickle.load(open(MODEL_PKL, "rb"))
    vec   = pickle.load(open(VEC_PKL,   "rb"))

    # Prefer label map from meta file (written by F6_v2.py)
    if os.path.exists(META_PKL):
        meta      = pickle.load(open(META_PKL, "rb"))
        label_map = meta["label_map"]
        info      = (f"Best C={meta['best_C']} · "
                     f"Test F1={meta['test_f1']:.4f} · "
                     f"ROC-AUC={meta.get('roc_auc', 'N/A')}")
    else:
        # Fallback for old pkl files generated by original F6.py
        label_map, probe_score = probe_detect_label_map(model, vec)
        info = f"Label map auto-detected via probes (score {probe_score}/20)"

    return model, vec, label_map, info


# ── Prediction ────────────────────────────────────────────────────
def predict(text: str, model, vec, label_map):
    cleaned = clean_text(text)
    if not cleaned.strip():
        return None, None, None
    X     = vec.transform([cleaned])
    raw   = int(model.predict(X)[0])
    label = label_map.get(raw, "UNKNOWN")
    try:
        proba     = model.predict_proba(X)[0]
        fake_class = [k for k, v in label_map.items() if v == "FAKE"][0]
        fake_idx   = list(model.classes_).index(fake_class)
        p_fake     = proba[fake_idx]
        p_real     = 1 - p_fake
        confidence = round((p_fake if label == "FAKE" else p_real) * 100, 1)
    except Exception:
        try:
            s          = model.decision_function(X)[0]
            confidence = round(1 / (1 + np.exp(-abs(s))) * 100, 1)
        except Exception:
            confidence = None
    return label, confidence, cleaned


# ════════════════════════════════════════════════════════════════
#  PAGE CONFIG
# ════════════════════════════════════════════════════════════════
st.set_page_config(
    page_title="Fake News Detector",
    page_icon="🔍",
    layout="centered",
    initial_sidebar_state="collapsed",
)

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;700;800&family=DM+Sans:wght@300;400;500&display=swap');

html, body, [class*="css"] { font-family: 'DM Sans', sans-serif; }

.stApp {
    background: linear-gradient(135deg, #0f0f1a 0%, #1a1a2e 50%, #16213e 100%);
    min-height: 100vh;
}
#MainMenu, footer, header { visibility: hidden; }

.hero-title {
    font-family: 'Syne', sans-serif;
    font-weight: 800;
    font-size: clamp(2rem, 5vw, 3.5rem);
    background: linear-gradient(90deg, #e0e0ff 0%, #a78bfa 50%, #38bdf8 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    line-height: 1.1;
    margin-bottom: 0.25rem;
}
.hero-sub {
    color: #94a3b8;
    font-size: 1.05rem;
    font-weight: 300;
    margin-bottom: 2rem;
}
.card {
    background: rgba(255,255,255,0.05);
    border: 1px solid rgba(255,255,255,0.1);
    border-radius: 20px;
    padding: 2rem;
    backdrop-filter: blur(10px);
    margin-bottom: 1.5rem;
}
.badge-real {
    display: inline-block;
    background: linear-gradient(135deg, #10b981, #059669);
    color: white;
    font-family: 'Syne', sans-serif;
    font-weight: 700;
    font-size: 1.5rem;
    padding: 0.6rem 2rem;
    border-radius: 50px;
    letter-spacing: 0.15em;
    box-shadow: 0 0 30px rgba(16,185,129,0.4);
}
.badge-fake {
    display: inline-block;
    background: linear-gradient(135deg, #ef4444, #b91c1c);
    color: white;
    font-family: 'Syne', sans-serif;
    font-weight: 700;
    font-size: 1.5rem;
    padding: 0.6rem 2rem;
    border-radius: 50px;
    letter-spacing: 0.15em;
    box-shadow: 0 0 30px rgba(239,68,68,0.4);
}
.conf-text { color: #cbd5e1; font-size: 0.95rem; margin-top: 0.75rem; }
.conf-bar-bg {
    background: rgba(255,255,255,0.1);
    border-radius: 50px;
    height: 10px;
    margin-top: 0.5rem;
    overflow: hidden;
}
textarea {
    background: rgba(255,255,255,0.06) !important;
    border: 1px solid rgba(255,255,255,0.15) !important;
    border-radius: 12px !important;
    color: #e2e8f0 !important;
    font-family: 'DM Sans', sans-serif !important;
    font-size: 1rem !important;
}
.stButton > button {
    background: linear-gradient(135deg, #7c3aed, #2563eb) !important;
    color: white !important;
    border: none !important;
    border-radius: 12px !important;
    font-family: 'Syne', sans-serif !important;
    font-weight: 700 !important;
    font-size: 1rem !important;
    padding: 0.65rem 2.5rem !important;
    letter-spacing: 0.05em !important;
    transition: all 0.2s ease !important;
    width: 100%;
}
.stButton > button:hover {
    transform: translateY(-2px) !important;
    box-shadow: 0 8px 25px rgba(124,58,237,0.45) !important;
}
.info-box {
    background: rgba(56,189,248,0.08);
    border-left: 3px solid #38bdf8;
    border-radius: 8px;
    padding: 0.85rem 1rem;
    color: #94a3b8;
    font-size: 0.88rem;
    margin-top: 1rem;
}
label, .stTextArea label { color: #cbd5e1 !important; font-weight: 500 !important; }
hr { border-color: rgba(255,255,255,0.08) !important; margin: 1.5rem 0; }
</style>
""", unsafe_allow_html=True)

# ════════════════════════════════════════════════════════════════
#  LOAD
# ════════════════════════════════════════════════════════════════
model, vec, label_map, model_info = load_model()

st.markdown('<div class="hero-title">🔍 Fake News Detector</div>', unsafe_allow_html=True)
st.markdown('<div class="hero-sub">Powered by LinearSVC · TF-IDF (word + char) · NLTK</div>',
            unsafe_allow_html=True)

if model is None:
    st.error(
        "**Model files not found.**\n\n"
        "Place `linsvm_model.pkl` and `tfidf_vectorizer.pkl` (and optionally `model_meta.pkl`) "
        "in the same folder as `app.py`, then rerun.\n\n"
        "Train the model first by running `F6_v2.py`."
    )
    st.stop()

# ════════════════════════════════════════════════════════════════
#  INPUT
# ════════════════════════════════════════════════════════════════
st.markdown('<div class="card">', unsafe_allow_html=True)
news_input = st.text_area(
    "Paste a news headline or article excerpt",
    placeholder="e.g.  Scientists discover water on Mars in latest NASA mission…",
    height=180,
    key="news_input",
)
analyse_btn = st.button("Analyse →", key="analyse")
st.markdown('</div>', unsafe_allow_html=True)

# ════════════════════════════════════════════════════════════════
#  RESULT
# ════════════════════════════════════════════════════════════════
if analyse_btn:
    if not news_input.strip():
        st.warning("Please enter some text before clicking Analyse.")
    else:
        with st.spinner("Analysing…"):
            label, confidence, cleaned = predict(news_input, model, vec, label_map)

        if label is None:
            st.warning("Text was too short or contained no usable words after cleaning.")
        else:
            st.markdown('<div class="card">', unsafe_allow_html=True)

            badge_cls = "badge-real" if label == "REAL" else "badge-fake"
            icon      = "✅" if label == "REAL" else "🚨"
            verdict   = "This article appears to be <b>REAL</b>." if label == "REAL" \
                        else "This article appears to be <b>FAKE</b>."

            st.markdown(f'<span class="{badge_cls}">{icon} {label}</span>',
                        unsafe_allow_html=True)

            if confidence is not None:
                bar_color = "#10b981" if label == "REAL" else "#ef4444"
                st.markdown(
                    f'<p class="conf-text">Confidence: <b>{confidence}%</b></p>'
                    f'<div class="conf-bar-bg">'
                    f'<div style="width:{confidence}%;height:10px;background:{bar_color};'
                    f'border-radius:50px;transition:width 0.6s ease;"></div></div>',
                    unsafe_allow_html=True,
                )

            st.markdown(f"<p style='color:#94a3b8;margin-top:1rem;'>{verdict}</p>",
                        unsafe_allow_html=True)

            with st.expander("🔬 Cleaned text sent to model"):
                st.code(cleaned, language=None)

            st.markdown('</div>', unsafe_allow_html=True)

# ════════════════════════════════════════════════════════════════
#  HOW IT WORKS
# ════════════════════════════════════════════════════════════════
with st.expander("ℹ️  How does this work?"):
    st.markdown(f"""
**Improvements in v2 model (F6_v2.py)**

| What changed | Why it reduces overfitting |
|---|---|
| GridSearchCV over C ∈ {{0.01…2.0}} | Finds the right regularization strength automatically |
| Word TF-IDF + Char TF-IDF (FeatureUnion) | Char n-grams catch spelling tricks in fake headlines |
| 50,000 word + 20,000 char features | More signal, less noise than 5,000 words alone |
| `min_df=5` (raised from 3) | Drops rare, over-fitted tokens |
| `class_weight='balanced'` | Corrects for class imbalance |
| CalibratedClassifierCV | Calibrated probabilities (not raw distances) |
| Title weighted 3× | Headlines are the most predictive feature |
| Learning-curve plot | Visual overfitting diagnosis saved to `results/` |

**Label map:** `{label_map}` · {model_info}

> ⚠️ Always verify news with primary sources.
    """)

st.markdown(
    f'<div class="info-box">Model: <b>CalibratedLinearSVC</b> &nbsp;|&nbsp; '
    f'Features: <b>Word (1–2 gram) + Char (2–4 gram) TF-IDF</b> &nbsp;|&nbsp; '
    f'{model_info}</div>',
    unsafe_allow_html=True,
)
